'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {openAnalytics}=require('./analytics.cjs');
const ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
test('real pageviews, dedup, active time, visit grouping, bots, owner exclusion, timezone boundaries',()=>{
  const a=openAnalytics(':memory:','test-salt');
  const now=Date.parse('2026-10-04T10:00:00+08:00');
  const body={pageId:crypto.randomUUID(),path:'/',utm:{source:'linkedin',campaign:'test'},referrer:'https://linkedin.com/feed?private=1',screen:'1440x900',seconds:0,kind:'pageview'};
  assert.equal(a.record(body,'v','8.8.8.8',ua,now),true);
  a.record({...body,seconds:1000},'v','8.8.8.8',ua,now+20000);
  a.record({...body,path:'/work.html',pageId:crypto.randomUUID(),seconds:0},'v','8.8.8.8',ua,now+30000);
  let stats=a.stats(7,now+40000);
  assert.equal(stats.totals.visitors,1);assert.equal(stats.totals.visits,1);assert.equal(stats.totals.pageviews,2);
  assert.equal(stats.recent[0].seconds,22);assert.equal(stats.sources[0].source,'linkedin');
  assert.deepEqual(stats.recent[0].pages,['/','/work.html']);
  assert.equal(stats.recent[0].referrer,'https://linkedin.com/feed');
  assert.equal(a.db.prepare('SELECT ip_hash FROM visits').get().ip_hash.includes('8.8.8.8'),false);
  assert.equal(a.record({...body,pageId:crypto.randomUUID(),path:'/admin'},'v','8.8.8.8',ua,now),false);
  assert.equal(a.record(body,'another','8.8.8.8',ua,now),false);
  a.record({...body,pageId:crypto.randomUUID()},'bot','8.8.8.8','Googlebot/2.1',now);
  assert.equal(a.stats(1,now).excludedBots,1);assert.equal(a.stats(1,now).totals.pageviews,2);
  a.record({...body,pageId:crypto.randomUUID()},'v','8.8.8.8',ua,now+31*60000+30000);
  assert.equal(a.stats(1,now+32*60000).totals.visits,2);
  a.record({...body,pageId:crypto.randomUUID()},'new','1.1.1.1',ua,Date.now());
  a.excludeOwner('new');assert.equal(a.db.prepare('SELECT COUNT(*) n FROM visits WHERE visitor=?').get(a.hash('new')).n,0);
  assert.equal(stats.series.length,7);assert.equal(stats.summary.length,3);
  assert.equal(a.stats(1,Date.parse('2026-10-05T00:00:00+08:00')).totals.pageviews,0);
  a.db.close();
});
